### ISSUE TITLE
Error in lvmClassVisualise

### ISSUE THREAD

**Issue by sinanmut** [SheffieldML/GPmat#10]
Hi,

I am trying to use the GPmat tool and check the plots, but when click on Figure1 (Latent Variables plot), I get an error as: 

Attempted to access visualiseInfo.latentPos(-0.909202); index must be a positive integer or logical.

Error in lvmClassVisualise (line 25)
    visualiseInfo.latentPos(visualiseInfo.dim1) = x;

Error while evaluating Figure WindowButtonDownFcn

Could it be because of the version of Matlab I have (2015a).

Thanks a lot.

Sinan

**Comment by adamian** [comment]
Hi,
Are you running a particular demo?

cheers,
Andreas

**Comment by lawrennd** [comment]
Closing due to lack of response
