### ISSUE TITLE
demRobotWireless4.m error

### ISSUE THREAD

**Issue by fxolivia** [SheffieldML/GPmat#16]
anyone got the result of demRobotWireless4.m shows in the main page of GPmat as following?
![image](https://user-images.githubusercontent.com/21353995/33308531-2c4b006c-d45e-11e7-9d06-9003b7e9f65b.png)
And this is what I got, 
![demrobotwireless4](https://user-images.githubusercontent.com/21353995/33308597-79706986-d45e-11e7-9348-160615037b5a.jpg)
not same with what they are showing, Can someone tell me what's going on?

**Comment by adamian** [comment]
One wouldn't be expected to get exactly the same results, unless fixing carefully all the random seeds and making sure they run on the same system. 

The important part is to make sure that all the obtained solutions make sense. From what I see in the plots, both solutions make sense to me: the latent space reflects the closed / circular loop with the little "tail" below corresponding to the first few steps of the robot. We know that the correct topology is somehow more rectangular, so the second plot might be a little more accurate, but perhaps the first plot could be improved with more iterations in the optimization or better initialization / care to avoid local minima. 

Does that help?

Andreas
