### ISSUE TITLE
L2_distance ???

### ISSUE THREAD

**Issue by mgh17** [SheffieldML/GPmat#18]
Hello, I downloaded your code in order to implement HopLand (https://github.com/NetLand-NTU/HopLand).

The code isn't running, there appears to be a problem with the L2_distance function being undefined in isomapEmbed (line 11).

Any help would be greatly appreciated, I'm new to this!

**Comment by adamian** [comment]
You can find it here: http://web.mit.edu/cocosci/isomap/code/L2_distance.m

**Comment by NetLand-NTU** [comment]
Hi mgh17,

I am Jie Zheng, the corresponding author of the HopLand paper. HopLand indeed uses the "IsomapR1" package which can be downloaded from the MIT website, as referred to by Mr. Andreas Damianou. The GitHub site of HopLand has been updated accordingly. I apologize for the confusion and inconvenience caused. 

Thank you both for your patience and help in resolving this issue.

Best regards,
Jie
