### ISSUE TITLE
mltools/isomapEmbed.m??

### ISSUE THREAD

**Issue by dong1206** [SheffieldML/GPmat#19]
The 'neighbours' parameter is set 7 in the latest version for this function, while its value is 10 in its previous version. Why did you change this parameter ‘'neighbours" from 10 to 7?

**Comment by lawrennd** [comment]
I don’t recall when this change was made, but it makes the initialisation ‘less linear’. E.g. if you send number of neighbours to $n$ you are doing PCA.
