### ISSUE TITLE
Reformulation variational lower bound in gpLogLikelihood.m

### ISSUE THREAD

**Issue by SimonEbner** [SheffieldML/GPmat#2]
Dear all,

first of all, thank you very much for providing your code as open source. It's very impressive and educational. I have a quick question concerning the calculation of the first part of the variational lower bound in gpLogLikelihood.m:54:

      ll =  -0.5*(model.d*(-(model.N-model.k)*log(model.beta) ...
                           - model.logDetK_uu +model.logdetA) ...
                  - (sum(sum(model.Ainv.*EET)) ...
                     -sum(sum(model.m.*model.m)))*model.beta)   ;

As far as I understand it, this is a reformulation of

     F = log[ N( y| 0, sigma^2 * I + Q_nn )] with Q_nn = K_nm / K_mm K_mn

Do you happen to have a article / paper for me which helps me understanding the mathmatical reformulation that are going on here?

Thank you very much in advance. 
Best,
Simon

**Comment by adamian** [comment]
Hi Simon,

Check these two papers:
[Titsias 09 - Variational Learning of Inducing Variables in Sparse Gaussian
Processes](http://jmlr.org/proceedings/papers/v5/titsias09a/titsias09a.pdf)
[Lawrence 07 - Learning for Larger Datasets with the Gaussian Process Latent Variable Model](http://jmlr.csail.mit.edu/proceedings/papers/v2/lawrence07a/lawrence07a.pdf)

Hope this helps!
Andreas

**Comment by SimonEbner** [comment]
Hi Andreas,

thank you very much, I hadn't looked at the second paper. It made things clear now.

Best, Simon
