### ISSUE TITLE
Multivariate capability?

### ISSUE THREAD

**Issue by sgbaird** [SheffieldML/GPmat#20]
Hi,

Is GPmat designed to handle multivariate observation data? Many of the examples show single-variable observations.

Sterling

**Comment by lawrennd** [comment]
HI Sterling,

Multivariate (in terms of multiple targets, or outputs) GPs are implemented in this package: https://github.com/SheffieldML/multigp

Although you can also implement a multi-output GP in a single output package by augmenting your covariance function input with an "output index" and building kernels to handle that. That's how the GPy software does it.

Neil

**Comment by sgbaird** [comment]
HI Neil,

Thanks for your response. What about for single-output, multivariate-input (i.e. each observation is a vector rather than a scalar)? Is this implemented in GPmat or would I need to move to multigp?

Sterling

**Comment by lawrennd** [comment]
That’s in GPmat as standard.
