### ISSUE TITLE
Suggestion - Add Netlab to GPmat?

### ISSUE THREAD

**Issue by asn196** [SheffieldML/GPmat#4]
Hi SheffieldML group,

Thankyou very much for providing such a thorough code which is useful at so many levels.There is a small issue/suggestion that I wanted to put forward though. I was getting errors when I simply downloaded GPmat and ran demos for FGPLVM, but adding the Netlab dependency solves the issue.

So, I wanted to suggest that if we add Netlab as part of GPmat it would just become a one stop shop where we wouldn't have to worry about errors and dependencies. I will mark it as resolved as soon as there is any comment because its basically a suggestion not an issue.

Thanks.

**Comment by lawrennd** [comment]
Hi,

It's an interesting idea. I actually hosted netlab on github having checked
with Ian that he was happy for me to. But I think it would be odd to
include it with GPmat ... it's independently developed.

I know it could make things more convenient on the dependencies front.

Neil
