### ISSUE TITLE
error with ppcaEmbed.m

### ISSUE THREAD

**Issue by TuBui** [SheffieldML/GPmat#5]
I try to run the demo function demOilFgplvm1.m. However it throws the following error:

Error using  * 
Inner matrix dimensions must agree.

Error in ppcaEmbed (line 50)
    X = Ycentre*u(:, 1:dims)*diag(1./sqrt(v(1:dims)));

Error in fgplvmCreate (line 30)
  X = initFunc(Y, q);

Error in demOilFgplvm1 (line 21)
model = fgplvmCreate(latentDim, d, Y, options);

The error comes from the function /mltools/ppcaEmbed.m. It shows that Ycentre has dimension 1000x12, u has dim 1000x2 and diag(1./sqrt(v(1:dims))) has dim 2x2; therefore these dimensions do not match. Can you explain this?

My Matlab version is R2015a.

**Comment by TuBui** [comment]
Ahh, I see. Matlab should call the ppcaEmbed function in the netlab package instead. The readme file should be updated to inform users that Netlab is still needed.

**Comment by adamian** [comment]
You're right, you're not the only one that has been confused by that. I've created a pull request, thanks for the comment.

**Comment by buaaCCJ** [comment]
@TuBui  Hi,is there the ppcaEmbed function in the netlab package? I can't find it.

**Comment by adamian** [comment]
@buaaCCJ ppcaEmbed is in GPmat: https://github.com/SheffieldML/GPmat/blob/master/mltools/ppcaEmbed.m
