### ISSUE TITLE
error with demCmu35gplvmReconstruct.m

### ISSUE THREAD

**Issue by TuBui** [SheffieldML/GPmat#6]
Hi SheffieldML group,
Thank you very much for releasing such useful toolbox. I have downloaded the code and successfully run the first fgplvm demo examples. However, I fail to execute the demCmu35gplvmReconstruct.m:

Reference to non-existent field 'indexAll'.

Error in gpDynamicsSequenceLogLikeGradient (line 59)
tmp = zeros(size(gX,1),length(model.indexAll));

Error in fgplvmSequenceLogLikeGradient (line 44)
    g = g + feval(model.dynamics, X);

Error in fgplvmSequenceGradient (line 26)
g = - fgplvmSequenceLogLikeGradient(model, X, Y, varargin{:});

Error in conjgrad (line 91)
gradnew = feval(gradf, x, varargin{:});

Error in fgplvmOptimiseSequence (line 51)
  Xout = optim('fgplvmSequenceObjective', X(:)',  options, ...

Error in fgplvmTaylorAngleErrors (line 59)
Xpred = fgplvmOptimiseSequence(model, Xinit, Ytest, 1, 1000);

The gplvm model was created using demCmu35gplvm1.m

**Comment by adamian** [comment]
That might be difficult to trace, I've done an ack-grep in all files of GPmat and "indexAll" only appears in that line... 
If I understand correctly, fgplvmOptimiseSequence is similar to fgplvmOptimisePoint but the points are correlated. In that context, indexAll might (?) denote which indexes of X form one (or more?) sequence(s). 
Sorry I haven't been able to help more, but it seems to me it has to do with indexing elements of X (e.g. 1:size(model.X,1) for the whole set treated as sequence).

**Comment by TuBui** [comment]
Thank you. I try fgplvmOptimisePoint as suggested and the error is gone.

**Comment by nimagh** [comment]
Do you think a fix for this in the main repo is appropriate?

**Comment by adamian** [comment]
Yes, I added it, thanks. But bear in mind that fgplvmOptimisePoint won't take sequential correlations into account, so the behaviour is not 100% the same.
